# Generated by Django 4.2.1 on 2025-02-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custadmin', '0003_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Policy', models.CharField(max_length=500)),
                ('booking_rules', models.CharField(max_length=500)),
                ('upload_document', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('Payment_id', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custadmin.employee')),
            ],
        ),
    ]
