# Generated by Django 4.2.1 on 2025-02-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='Payment_id',
            new_name='status',
        ),
    ]
