# Generated by Django 4.2.1 on 2024-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider_name', models.CharField(max_length=100)),
                ('Service_Provider_Address', models.CharField(max_length=100)),
                ('Service_Provider_Email', models.CharField(max_length=100)),
                ('Service_Provider_Phone', models.CharField(max_length=100)),
                ('Service_Provider_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('service_table', models.IntegerField()),
                ('Service_Provider_Experience', models.CharField(max_length=100)),
                ('Service_Provider_Id_proof', models.FileField(upload_to='images/')),
                ('photo', models.ImageField(upload_to='images/')),
                ('Service_Provider_Qualification_Certificate', models.FileField(upload_to='images/')),
                ('status', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
