# Generated by Django 4.2.1 on 2024-07-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
