# Generated by Django 4.2.1 on 2024-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_service_provider_service_provider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider',
            name='Service_Provider_amountdefalult',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
