# Generated by Django 4.2.1 on 2024-08-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerlogin', '0005_booking_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_end_date',
        ),
    ]
