# Generated by Django 4.2.1 on 2024-08-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerlogin', '0006_remove_booking_service_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_start_date',
        ),
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_start_date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_dates', to='customerlogin.booking')),
            ],
        ),
    ]
