# Generated by Django 4.2.1 on 2024-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerlogin', '0007_remove_booking_service_start_date_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdate',
            name='time_slot',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('FULL_DAY', 'Full Day')], default='FULL_DAY', max_length=10),
        ),
    ]
