# Generated by Django 4.2.1 on 2024-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerlogin', '0008_bookingdate_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='time_slot',
            field=models.CharField(default='FULL_DAY', max_length=10),
        ),
    ]
