# Generated by Django 4.2.1 on 2024-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerlogin', '0009_alter_bookingdate_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
