# Generated by Django 4.2.1 on 2024-08-18 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerlogin', '0011_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('status', models.CharField(max_length=100)),
                ('certificate_qualification', models.FileField(upload_to='images/')),
                ('previous_job_work', models.FileField(upload_to='images/')),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_id', models.CharField(max_length=500)),
                ('transactiondate', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerlogin.booking')),
            ],
        ),
    ]
