# Generated by Django 4.2.1 on 2024-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='transactiondate',
            field=models.DateField(),
        ),
    ]
