# Generated by Django 4.2.1 on 2024-07-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custadmin', '0003_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
