# Generated by Django 4.2.1 on 2024-08-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerlogin', '0011_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoriesbuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Additionalaccessoriesamount', models.CharField(max_length=100)),
                ('proofupdate', models.ImageField(upload_to='images/')),
                ('update_date', models.DateTimeField()),
                ('Booking1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerlogin.booking')),
            ],
        ),
    ]
