# Generated by Django 4.2.1 on 2024-09-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_service_provider_service_provider_amountdefalult'),
        ('customserviceprovider', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='serviceprovider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.service_provider'),
            preserve_default=False,
        ),
    ]
